content:
  - name: notes
    label: Notes
    path: _notes
    type: collection
  - name: posts
    label: Posts
    path: _posts
    type: collection
  - name: reviews
    label: reviews
    path: _reviews
    type: collection


media: assets/images