url: 'https://gavey.ca'
baseurl: ''
title: 'Gavey.ca'

collections:
  posts:
    output: true
    permalink: /posts/:year/:title/
  notes:
    output: true
    permalink: /notes/:year/:title/

future: true

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - old_site