url: 'https://gavey.ca'
baseurl: ''
title: 'Syntax and Subplots'

collections:
  posts:
    output: true
    permalink: /posts/:year/:title/
  notes:
    output: true
    permalink: /notes/:year/:title/
  reviews:
    output: true
    permalink: /reviews/:year/:title/

future: true

plugins:
  - jekyll-postcss
  - jekyll-feed

postcss:
  cache: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Derek Gavey"
  - scope:
      path: ""
      type: "notes"
    values:
      author: "Derek Gavey"
  - scope:
      path: ""
      type: "reviews"
    values:
      author: "Derek Gavey"
feed:
  collections:
    - notes
    - reviews

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - old_site
  - scripts