url: ''
baseurl: ''
title: 'Gavey.ca'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - old_site